repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format
        args: [src/, tests/]
        language: system
        pass_filenames: false
        types: [python]

      - id: ruff-check
        name: ruff check
        entry: ruff check
        args: [src/, tests/]
        language: system
        pass_filenames: false
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        args: [src/, tests/]
        language: system
        pass_filenames: false
        types: [python]
